services:
  mongo:
    image: mongo:7
    restart: unless-stopped
    volumes:
      - mongo-data:/data/db

  backend:
    build: ./backend
    image: kraneelmanandhar/backend:v1.0
    environment:
      PORT: 5000
      MONGO_URI: mongodb://mongo:27017/simple-mern-todo
    ports:
    
      - "5000:5000"
    depends_on:
      - mongo

  frontend:
    build:
      context: ./frontend
      args:
        VITE_API_URL: http://localhost:5000/api
    image: kraneelmanandhar/frontend:v1.0
    ports:
      - "5173:80"
    depends_on:
      - backend

volumes:
  mongo-data: