name: Backend CI/CD

on:
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build and push Docker image
        run: bash scripts/build-and-push.sh
        env:
          DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USER }}
          DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
          IMAGE: todo-repo
          CONTEXT: ./backend

  deploy:
    needs: build-and-push
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy to EC2
        run: bash scripts/deploy.sh
        env:
          DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USER }}
          DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
          IMAGE: todo-repo
          CONTAINER: todo-backend
          PORT: 4200
          EXTRA_DOCKER_ARGS: "-e MONGO_URI=mongodb+srv://aarsh123gautam_db_user:vgXyhTgTPaQSq5tw@cluster0.qwk7d0c.mongodb.net/test --network todo-network"
          EC2_HOST: ${{ secrets.EC2_HOST }}
          EC2_USER: ${{ secrets.EC2_USER }}
          EC2_SSH_KEY: ${{ secrets.EC2_SSH_KEY }}

