name: Hello

on: push # run on every push

jobs:
  greet:
    runs-on: ubuntu-latest # a fresh Linux machine
    steps: # This must be indented to be inside 'greet'
      - name: Say hello
        run: echo "Hello from GitHub Actions"
